name: Build Pipenv

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-pipenv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          file: tools/docker/pipenv.Dockerfile
